import React, { useState, useEffect } from 'react';
import { 
  History, 
  Search, 
  Printer, 
  Filter, 
  Calendar,
  Clock,
  User,
  ShieldCheck,
  FileText,
  Loader2,
  ChevronRight,
  Download
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { db, handleFirestoreError, OperationType } from '../../lib/firebase';
import { collection, query, onSnapshot, orderBy, limit, where } from 'firebase/firestore';
import { cn } from '../../lib/utils';
import { useFirebase } from '../../lib/FirebaseProvider';

export default function ActivityLog() {
  const [logs, setLogs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterType, setFilterType] = useState('ALL');
  const { user } = useFirebase();

  useEffect(() => {
    setLoading(true);
    const qLogs = query(collection(db, 'activity_log'), orderBy('timestamp', 'desc'));
    const unsubLogs = onSnapshot(qLogs, (snapshot) => {
      setLogs(snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })));
      setLoading(false);
    }, (error) => {
      handleFirestoreError(error, OperationType.LIST, 'activity_log');
      setLoading(false);
    });

    return () => unsubLogs();
  }, []);

  const filteredLogs = logs.filter(log => {
    const matchesSearch = 
      log.userName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      log.details?.toLowerCase().includes(searchTerm.toLowerCase()) ||
      log.type?.toLowerCase().includes(searchTerm.toLowerCase());
    
    const matchesFilter = filterType === 'ALL' || log.type === filterType;
    
    return matchesSearch && matchesFilter;
  });

  const printActivityLog = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const logRows = filteredLogs.map(log => `
      <tr>
        <td>${new Date(log.timestamp).toLocaleString()}</td>
        <td><span class="type-badge">${log.type.replace('_', ' ')}</span></td>
        <td>${log.userName || 'N/A'}</td>
        <td>${log.details}</td>
      </tr>
    `).join('');

    printWindow.document.write(`
      <html>
        <head>
          <title>Activity Log Report - ${new Date().toLocaleDateString()}</title>
          <style>
            body { font-family: 'Helvetica', 'Arial', sans-serif; padding: 40px; color: #1e293b; }
            .header { border-bottom: 3px solid #1e293b; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: flex-end; }
            .title { font-size: 24px; font-weight: 900; text-transform: uppercase; margin: 0; color: #1e293b; }
            .meta { font-size: 10px; color: #64748b; margin-top: 5px; text-transform: uppercase; font-weight: 700; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { text-align: left; background: #f8fafc; padding: 12px; font-size: 10px; font-weight: 900; text-transform: uppercase; color: #64748b; border-bottom: 2px solid #e2e8f0; }
            td { padding: 12px; font-size: 11px; border-bottom: 1px solid #f1f5f9; vertical-align: top; }
            .type-badge { font-weight: 900; font-size: 9px; color: #1e293b; text-transform: uppercase; }
            .footer { margin-top: 50px; border-top: 1px solid #e2e8f0; padding-top: 20px; font-size: 10px; color: #94a3b8; text-align: center; }
            @media print { @page { margin: 1cm; } }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <h1 class="title">Official Activity Log</h1>
              <div class="meta">Municipal Audit Record • Jalajala Municipal GIS</div>
            </div>
            <div style="text-align: right">
              <div class="meta">Generated By: ${user?.email}</div>
              <div class="meta">Date: ${new Date().toLocaleString()}</div>
            </div>
          </div>
          <table>
            <thead>
              <tr>
                <th style="width: 150px">Timestamp</th>
                <th style="width: 120px">Event Type</th>
                <th style="width: 150px">User</th>
                <th>Activity Details</th>
              </tr>
            </thead>
            <tbody>
              ${logRows || '<tr><td colspan="4" style="text-align: center">No activities recorded in this period.</td></tr>'}
            </tbody>
          </table>
          <div class="footer">
            CONFIDENTIAL DOCUMENT • OFFICE OF THE MUNICIPAL ENGINEER • JALAJALA, RIZAL
          </div>
          <script>window.print();</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="max-w-7xl mx-auto py-12 px-4 sm:px-8">
      {/* Header section with Stats */}
      <div className="bg-white p-8 rounded-2xl shadow-xl border-t-4 border-brand-blue mb-12 flex flex-col md:flex-row justify-between items-center gap-8">
        <div>
          <div className="flex items-center gap-3 mb-2">
            <History size={32} className="text-brand-blue" />
            <h2 className="text-2xl font-black text-brand-blue uppercase tracking-tight">MUNICIPAL ACTIVITY AUDIT</h2>
          </div>
          <p className="text-slate-500 font-bold text-sm tracking-tight italic">
            "Maintaining administrative transparency through comprehensive temporal tracking and record-keeping."
          </p>
        </div>
        <div className="flex gap-4">
          <div className="bg-slate-50 px-6 py-4 rounded-xl border border-slate-100 text-center">
             <div className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Total Logs</div>
             <div className="text-2xl font-black text-brand-blue">{logs.length}</div>
          </div>
          <button 
            onClick={printActivityLog}
            className="px-8 py-5 bg-brand-blue text-white text-[10px] font-black rounded-xl border-b-4 border-slate-900 hover:translate-y-px hover:border-b-2 transition-all flex items-center gap-4 shadow-xl"
          >
            <Printer size={18} /> PRINT AUDIT REPORT
          </button>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="bg-white p-4 rounded-xl border border-slate-200 shadow-sm mb-8 flex flex-col md:flex-row gap-4">
        <div className="flex-grow relative">
          <Search className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
          <input 
            type="text"
            placeholder="Search logs by name, type, or details..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full pl-12 pr-4 py-3 bg-slate-50 border border-slate-200 rounded-lg text-sm font-bold focus:border-brand-blue outline-none transition-all"
          />
        </div>
        <div className="shrink-0 flex gap-2">
          <div className="relative">
             <Filter className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400" size={14} />
             <select 
              value={filterType}
              onChange={(e) => setFilterType(e.target.value)}
              className="pl-10 pr-8 py-3 bg-slate-50 border border-slate-200 rounded-lg text-[10px] font-black uppercase tracking-widest outline-none appearance-none hover:bg-slate-100 transition-colors w-48"
             >
               <option value="ALL">ALL CATEGORIES</option>
               <option value="CITIZEN_REGISTRATION">CITIZEN REGISTRATION</option>
               <option value="ADMIN_ACTION">ADMIN ACTIONS</option>
               <option value="SYSTEM">SYSTEM EVENTS</option>
             </select>
          </div>
        </div>
      </div>

      {/* Activity Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        {loading ? (
          <div className="py-24 text-center">
            <Loader2 className="animate-spin text-brand-blue mx-auto mb-4" size={48} />
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Compiling Historical Data...</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-100">
                  <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Temporal Stamp</th>
                  <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Classification</th>
                  <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Individual Involved</th>
                  <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Transaction Details</th>
                  <th className="px-6 py-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">Audit</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-50">
                {filteredLogs.length === 0 ? (
                  <tr>
                    <td colSpan={5} className="py-24 text-center">
                      <div className="text-[10px] font-black text-slate-300 uppercase tracking-widest">No matching activities found for current filters.</div>
                    </td>
                  </tr>
                ) : (
                  filteredLogs.map((log) => (
                    <motion.tr 
                      key={log.id}
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="hover:bg-slate-50/50 transition-colors group"
                    >
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center gap-2">
                          <Clock size={14} className="text-brand-blue" />
                          <div>
                            <div className="text-[11px] font-bold text-slate-900">{new Date(log.timestamp).toLocaleDateString()}</div>
                            <div className="text-[9px] font-bold text-slate-400">{new Date(log.timestamp).toLocaleTimeString()}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <span className={cn(
                          "px-2 py-1 rounded text-[9px] font-black uppercase tracking-wider",
                          log.type === 'CITIZEN_REGISTRATION' ? "bg-emerald-50 text-emerald-600 border border-emerald-100" :
                          log.type === 'ADMIN_ACTION' ? "bg-blue-50 text-blue-600 border border-blue-100" :
                          "bg-slate-50 text-slate-600 border border-slate-100"
                        )}>
                          {log.type.replace('_', ' ')}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2">
                          <div className="w-6 h-6 rounded-full bg-brand-blue/10 flex items-center justify-center text-brand-blue">
                            <User size={12} />
                          </div>
                          <div>
                            <div className="text-[11px] font-black text-slate-900 uppercase tracking-tight">{log.userName}</div>
                            <div className="text-[8px] font-bold text-slate-400 truncate max-w-[120px]">{log.userId}</div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <p className="text-[11px] font-medium text-slate-600 max-w-sm leading-relaxed">{log.details}</p>
                      </td>
                      <td className="px-6 py-4">
                         <div className="flex items-center gap-1 text-[9px] font-black text-brand-gold uppercase opacity-0 group-hover:opacity-100 transition-opacity">
                           VERIFIED <ShieldCheck size={10} />
                         </div>
                      </td>
                    </motion.tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Audit Footer */}
      <div className="mt-8 bg-slate-50 p-6 rounded-xl border border-dashed border-slate-200">
         <div className="flex items-center gap-4 text-slate-400">
            <ShieldCheck size={24} className="shrink-0" />
            <p className="text-[10px] font-bold leading-relaxed uppercase tracking-widest">
              Automated Integrity Protocol: This activity log records all critical transactions within the Municipal GIS Portal. 
              Records are immutably preserved and time-stamped according to official server time standards.
            </p>
         </div>
      </div>
    </div>
  );
}
